<?php

/**
 * @file
 * Hook implementations for the cmc module.
 */

declare(strict_types=1);

use Drupal\cmc\EntityCacheTagCollector;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_load().
 */
function cmc_entity_load(array $entities, $entity_type_id) {
  $is_disabled = \Drupal::config('cmc.settings')->get('operation_mode') === 'disabled';
  if ($is_disabled) {
    return;
  }
  $entity_cache_tag_collector = \Drupal::service(EntityCacheTagCollector::class);
  assert($entity_cache_tag_collector instanceof EntityCacheTagCollector);

  $content_entities = array_filter(
    $entities,
    static fn (EntityInterface $entity) =>
      $entity->getConfigDependencyKey() === 'content'
  );
  array_map([$entity_cache_tag_collector, 'registerLoadedEntity'], $content_entities);
}
