<?php

/**
 * @file
 * Hook implementations for the cmc module.
 */

declare(strict_types=1);

use Drupal\cmc\EntityCacheTagCollector;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_load().
 */
function cmc_entity_load(array $entities, $entity_type_id) {
  $is_disabled = \Drupal::config('cmc.settings')->get('operation_mode') === 'disabled';
  if ($is_disabled) {
    return;
  }
  foreach ($entities as $entity) {
    assert($entity instanceof EntityInterface);
    $entity_cache_tag_collector = \Drupal::service(EntityCacheTagCollector::class);
    assert($entity_cache_tag_collector instanceof EntityCacheTagCollector);
    $entity_cache_tag_collector->registerLoadedEntity($entity);
  }
}
